name: â© Sync develop with branches
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  sync:
    name: â© Sync branch
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: ðŸªª Set git name+email
        run: |
          git config user.name "Jack (GitHub Actions)"
          git config user.email "jack@noquarter.co"
      - name: ðŸ›£ Merge
        run: |
          current_branch="origin/develop"
          invite_branch="feat/invite-codes"
          urbanist_branch="urbanist"
          nextjs_branch="nextjs"
          echo "ðŸªœ Merging ${current_branch} -> ${invite_branch}"
          git checkout "${invite_branch}"
          git merge "${current_branch}"
          git push
          git checkout "${urbanist_branch}"
          git merge "${current_branch}"
          git push
          git checkout "${nextjs_branch}"
          git merge "${current_branch}"
          git push
